// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4NZ3yt283IaGw3jmYc-mYTqQyjIIWk0',
    appId: '1:406032902985:web:15e1f71f8a6199f9ed4898',
    messagingSenderId: '406032902985',
    projectId: 'swipe-ranks',
    authDomain: 'swipe-ranks.firebaseapp.com',
    storageBucket: 'swipe-ranks.firebasestorage.app',
    measurementId: 'G-F3TEZ4X4W5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBMTgjDTxIYIxHbL0HAFexCxvrj466OfE',
    appId: '1:406032902985:ios:b8e0d9844d1facf1ed4898',
    messagingSenderId: '406032902985',
    projectId: 'swipe-ranks',
    storageBucket: 'swipe-ranks.firebasestorage.app',
    iosBundleId: 'com.myrating.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP4NZ3yt283IaGw3jmYc-mYTqQyjIIWk0',
    appId: '1:406032902985:web:8e80c24de327d027ed4898',
    messagingSenderId: '406032902985',
    projectId: 'swipe-ranks',
    authDomain: 'swipe-ranks.firebaseapp.com',
    storageBucket: 'swipe-ranks.firebasestorage.app',
    measurementId: 'G-0J52H9WSW9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBMTgjDTxIYIxHbL0HAFexCxvrj466OfE',
    appId: '1:406032902985:ios:a197f9f34ca46237ed4898',
    messagingSenderId: '406032902985',
    projectId: 'swipe-ranks',
    storageBucket: 'swipe-ranks.firebasestorage.app',
    androidClientId: '406032902985-06n17vusmsjn8kcrb3utt2mv5iips6qe.apps.googleusercontent.com',
    iosClientId: '406032902985-ghc4k88tsdtprh0gnql6misa660f4kv2.apps.googleusercontent.com',
    iosBundleId: 'com.myrating.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARLbTaK-GDfvkdtfIhhpAhbWXuxsLx1r4',
    appId: '1:406032902985:android:3db40bbd3c76d9f6ed4898',
    messagingSenderId: '406032902985',
    projectId: 'swipe-ranks',
    storageBucket: 'swipe-ranks.firebasestorage.app',
  );

}