// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgBlHqjlWzabqQdupkhb3sngeHu4GgS8o',
    appId: '1:331120007099:web:cb282fe4fa5ed5d2e9969e',
    messagingSenderId: '331120007099',
    projectId: 'myratingsystem',
    authDomain: 'myratingsystem.firebaseapp.com',
    storageBucket: 'myratingsystem.firebasestorage.app',
    measurementId: 'G-2CEJS52VZM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rHgFCY_GxsG-nBdi8VdThyX11BdBei8',
    appId: '1:331120007099:ios:5c419c07a392442ae9969e',
    messagingSenderId: '331120007099',
    projectId: 'myratingsystem',
    storageBucket: 'myratingsystem.firebasestorage.app',
    iosBundleId: 'com.myrating.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgBlHqjlWzabqQdupkhb3sngeHu4GgS8o',
    appId: '1:331120007099:web:360c623291d8b43fe9969e',
    messagingSenderId: '331120007099',
    projectId: 'myratingsystem',
    authDomain: 'myratingsystem.firebaseapp.com',
    storageBucket: 'myratingsystem.firebasestorage.app',
    measurementId: 'G-06G9V5LHP6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rHgFCY_GxsG-nBdi8VdThyX11BdBei8',
    appId: '1:331120007099:ios:5c419c07a392442ae9969e',
    messagingSenderId: '331120007099',
    projectId: 'myratingsystem',
    storageBucket: 'myratingsystem.firebasestorage.app',
    iosBundleId: 'com.myrating.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wGudhx064I82K7tIzb3IPL0YNplEmRY',
    appId: '1:331120007099:android:67b1171aabb0dc73e9969e',
    messagingSenderId: '331120007099',
    projectId: 'myratingsystem',
    storageBucket: 'myratingsystem.firebasestorage.app',
  );

}